---
abstract: 'PGXN API full text search interface'
author:
  - 'David E. Wheeler <david.wheeler@pgexperts.com>'
build_requires:
  File::Path: 2.08
  File::Spec::Functions: 0
  Module::Build: 0.30
  Test::More: 0.96
configure_requires:
  Module::Build: 0.30
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PGXN-API-Searcher
provides:
  PGXN::API::Searcher:
    file: lib/PGXN/API/Searcher.pm
    version: v0.10.1
recommends:
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.06
requires:
  Carp: 0
  File::Spec: 0
  Lucy: 0.002001
  perl: 5.01
resources:
  bugtracker: http://github.com/theory/pgxn-api-searcher/issues/
  homepage: http://search.cpan.org/dist/PGXN-API-Searcher/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/pgxn-api-searcher/tree/
version: v0.10.1
